### PR TITLE
fix(scripts): fix root check on start_acestream

### PR DESCRIPTION
**Pull request by frasurf**
fix mkdir on build.sh, on RPi-OSMC the unzip command doesn't create dir automatically

### CODE REVIEW

**Comment by miltador** [comment]
@frasurf, good catch and PR description! Thanks! Aside from PR, does the built distributable work on Raspberry Pi?

**Comment by frasurf** [comment]
Hi @miltador ! I'm trying right now, I'll let you know

**Comment by frasurf** [comment]
Works perfectly!!! Now I'm making some modification to adapt it to work with Plexus (Kodi Addon). 
It needs a stop_acestream.sh

**Comment by miltador** [comment]
Cool! Feel free to open PR for that. I haven't made any public announcement of this project yet, however will do, maybe​ there are more people interested in this.

**Pull request merged**
